# Default values for activiti-cloud-platform-quickstart in Jenkins-X.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  keycloak:
    ## Configure Activiti Keycloak host template, i.e. "activiti-keycloak.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: ""

    ## Set full url to configure external Keycloak, https://my.keycloak.com/auth
    # if not set, keycloak deployment is automatically exposed on gaetway host, i.e. http://activiti-cloud-gateway.REPLACEME/auth
    url: ""

    ## Configure Keycloak realm
    realm: "activiti"
    resource: "activiti"
    client: "activiti"

  gateway:
    ## Set to configure single domain name for all services, i.e. "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: "activiti-cloud-gateway.{{ .Release.Name }}.{{ .Values.global.gateway.domain }}"

    ## Set enable TLS configuration on all exposed service ingresses
    http: true

    ## Set to configure gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    #  helm upgrade activiti . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: "REPLACEME"

    ## Configure global annotations for all service ingresses, i.e. 
    annotations: 
      certmanager.k8s.io/issuer: letsencrypt-prod
    
activiti-cloud-modeling:
  enabled: true

application:
  runtime-bundle:
    enabled: true
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-query:
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-connector:
    enabled: true
    image:
      pullPolicy: Always

  activiti-cloud-notifications-graphql:
    enabled: true
    image:
      pullPolicy: Always

  activiti-cloud-audit:
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

infrastructure:
  activiti-keycloak:
    enabled: true
    ingress:
      enabled: true
    keycloak:
      enabled: true
      keycloak:
        preStartScript: |
          /opt/jboss/keycloak/bin/add-user.sh -u admin -p admin
          /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin
          cp /realm/activiti-realm.json .
          sed -i 's/placeholder.com/*/g' activiti-realm.json
  
  activiti-cloud-gateway:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "*"
        nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
